class Competition:
    def __init__(self, json: dict):
        self.game_id = json['GameId']
        self.away_team_id = json['AwayTeamId']
        self.home_team_id = json['HomeTeamId']
        self.home_team_score = json['HomeTeamScore']
        self.away_team_score = json['AwayTeamScore']
        self.home_team_city = json['HomeTeamCity']
        self.away_team_city = json['AwayTeamCity']
        self.home_team_name = json['HomeTeamName']
        self.away_team_name = json['AwayTeamName']
        self.start_date = json['StartDate']
        self.location = json['Location']
        self.last_play = json['LastPlay']
        self.team_with_possession = json['TeamWithPossession']
        self.time_reamining_status = json['TimeRemainingStatus']
        self.sport = json['Sport']
        self.status = json['Status']
        self.description = json['Description']
        self.full_description = json['FullDescription']
        self.exceptional_messages = json['ExceptionalMessages']
        self.series_type = json['SeriesType']
        self.number_of_games_in_series = json['NumberOfGamesInSeries']
        self.series_info = json['SeriesInfo']
        self.home_team_competition_ordinal = json['HomeTeamCompetitionOrdinal']
        self.away_team_competition_ordinal = json['AwayTeamCompetitionOrdinal']
        self.home_team_competition_count = json['HomeTeamCompetitionCount']
        self.away_team_competition_count = json['AwayTeamCompetitionCount']